name: Cypress Tests

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user 1001

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.9.0'

    - name: Install Dependencies
      run: npm install

    - name: Run Cypress Tests on Chrome
      run: npm run test-on-chrome

    - name: Run Cypress Tests on Firefox
      run: npm run test-on-firefox
